Repository tdesign-blazor/TDesignBlazor, pull requests merged in 2022-12, with the labels that each got.

#175 【新增】Affix 固钉组件
  doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesign.Docs.Shared/Pages/Components/AffixPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/SwitchPage.razor
  src/TDesign/Components/TAffix.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: 组件

#192 fixBug readme.md
  readme.md
Labels: size/XS, Extra Small

#193 docs: 更新了贡献指南和 pr 模板
  .github/pull_request_template.md
  .github/workflows/pr-conflict
  .github/workflows/pr-title-commit.yml
  .github/workflows/release-note-preview.yml
  Contributing.md
  LICENSE.md
  asset/kanban-drag.png
  asset/kanban-update-status.png
  pull_request_template.md
Labels: size/L, Medium

#197 ci: 更新git action某些文件
  .github/workflows/git-version.yml
  .github/workflows/pr-conflict.yml
  .github/workflows/pull-request.yml
  .github/workflows/release-note-preview.yml
  .gitignore
Labels: DevOps, size/M, Small

#198 fix: pull-request 加判断条件触发
  .github/workflows/pull-request.yml
Labels: DevOps, size/XS, Extra Small

#196 fix: Dialog 对话框关闭按钮位置错误
  src/TDesign/Components/TDialog.cs
Labels: Extra Small, size/S

#184 feat: 新增 Anchor 锚点组件
  doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
  doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesign.Docs.Shared/Pages/Components/AnchorPage.razor
  src/TDesign/Components/Anchor/TAnchor.cs
  src/TDesign/Components/Anchor/TAnchorItem.cs
  src/TDesign/Components/TLink.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: size/L, Large

#199 docs: 修改 ISSUE 模板
  .github/ISSUE_TEMPLATE/component-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: Extra Small, size/S

#200 fix: Message以及 Notification 无法定时关闭的bug
  src/TDesign/Components/Notify/Abstractions/NotifyContainerComponentBase.cs
Labels: 缺陷, Extra Small, size/S

#203 feat: 新增一个 release-drafter.yml
  .github/release-drafter.yml
  .github/workflow/draft-release-note.yml
Labels: Extra Small, size/M

#201 docs: 定义组件的api列表
  doc/TDesign.Docs.ServerSide/Pages/_Layout.cshtml
  doc/TDesign.Docs.ServerSide/TDesign.Docs.ServerSide.csproj
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Components/ComponentAPI.razor
  doc/TDesign.Docs.Shared/Components/Example.razor
  doc/TDesign.Docs.Shared/Layouts/LayoutContent.razor
  doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
  doc/TDesign.Docs.Shared/Pages/Components/AffixPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/AlertPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/AnchorPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/AvatarPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/BadgePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/BreadcrumbPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/ButtonPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/CardPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/CollapsePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/CommentPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/DialogPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/DividerPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/FormPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/GridPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/IconPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/ImagePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/InputAdornmentPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/InputCheckboxPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/InputNumberPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/InputRadioPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/InputRangePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/InputTextAreaPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/InputTextPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/LayoutPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/LinkPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/ListPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/LoadingPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/MenuPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/MessagePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/NotificationPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/PaginationPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/PopupPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/ProgressPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/SkeletonPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/SpacePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/StepPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/SwitchPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/TabPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/TablePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/TagPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/TimelinePage.razor
  doc/TDesign.Docs.Shared/Pages/Startup/Index.razor
  src/TDesign/Components/Anchor/TAnchor.cs
  src/TDesign/Components/Anchor/TAnchorItem.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: release/minor, Extra Large, size/XL

#202 feat(ci): 增加 release-note-drefter.yml
  .github/release-drafter.yml
  .github/workflows/draft-release-note.yml
Labels: size/M, Small, release/patch

#205 bugfix(ci): 更新 release-drafter.yml
  .github/release-drafter.yml
Labels: Extra Small, size/S, release/skip

#204 feat: 新增 TSelect 下拉菜单组件
  doc/TDesign.Docs.Shared/App.razor
  doc/TDesign.Docs.Shared/Components/ComponentAPI.razor
  doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesign.Docs.Shared/Pages/Components/SelectPage.razor
  src/TDesign/Components/Forms/TSelect.razor
  src/TDesign/Components/Forms/TSelect.razor.cs
  src/TDesign/Components/Popup/TPopup.cs
  src/TDesign/TDesignComponentBase.cs
Labels: 功能, size/L, Large, minor, feature

#209 feat: 新增暗黑和浅色模式切换
  doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
  doc/TDesign.Docs.Shared/wwwroot/app.css
  src/TDesign/TDesignExtensions.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: size/M, Small, feature, major

#210 fix: 修复 Popup 组件右箭头显示错误
  .github/release-drafter.yml
  src/TDesign/Components/Popup/Popper.cs
  src/TDesign/Components/Popup/PopperExtensions.cs
  src/TDesign/Components/Popup/PopperInstance.cs
  src/TDesign/Components/Popup/PopperOptions.cs
  src/TDesign/Components/Popup/TPopup.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: bug, size/L, Medium, patch

#212 feat: 新增 TPopConfirm 气泡对话框组件
  .github/release-drafter.yml
  doc/TDesign.Docs.Shared/Components/ComponentAPI.razor
  doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
  doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesign.Docs.Shared/Pages/Components/PopConfirmPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/PopupPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/TooltipPage.razor
  src/TDesign/Components/Popup/PopperOptions.cs
  src/TDesign/Components/Popup/TPopup.cs
  src/TDesign/Components/TButton.cs
  src/TDesign/Components/TPopConfirm.cs
  src/TDesign/Components/TTooltip.cs
  src/TDesign/Enum/Theme.cs
  src/TDesign/TDesignComponentBase.cs
Labels: feature, Large, size/XL, minor, 功能, 组件

#216 style: 升级 tdesign.css 到 1.0.2 版本
  package.json
  src/TDesign/wwwroot/tdesign.css
  src/TDesign/wwwroot/tdesign.css.map
  src/TDesign/wwwroot/tdesign.min.css
  src/TDesign/wwwroot/tdesign.min.css.map
  yarn.lock
Labels: feature, size/L, Extra Large, major

#217 chore(ci): 新增 pr-commit-label.yml 文件
  .github/workflows/pr-commit-label.yml
Labels: bug, feature, Extra Small, size/M, release/skip, minor, patch, chore
