Repository tdesign-blazor/TDesignBlazor, pull requests merged in 2022-10, with the labels that each got.

#115 Link 的单元测试
  TDesignBlazor.sln
  src/TDesignBlazor.Test/Components/LinkTest.cs
Labels: 单元测试

#118 【更新】PR 模板、贡献模板、readme
  .github/PULL_REQUEST_TEMPLATE/Pull_Request_Template.md
  .github/pull_request_template.md
  Contributing.md
  asset/tdesign-blazor.jpg
  pull_request_template.md
Labels: 文档, 完善

#119 【新增】Divider 组件的单元测试
  readme.md
  src/TDesignBlazor.Test/Components/DividerTest.cs
  src/TDesignBlazor.Test/TestBase.cs
  src/TDesignBlazor/Components/Divider.cs
Labels: 单元测试

#120 【新增】Avatar 和 AvatarGroup 单元测试
  src/TDesignBlazor.Test/Components/AvatarTest.cs
  src/TDesignBlazor.Test/TestBase.cs
Labels: 单元测试

#122 【新增】Badge 组件的单元测试并修复了样式错误的 bug
  src/TDesignBlazor.Test/Components/BadgeTest.cs
  src/TDesignBlazor/Components/Badge.cs
Labels: 单元测试

#126 【新增】可以使用 IMessageService 动态调用 Message 组件
  doc/TDesignBlazor.Docs.Shared/App.razor
  doc/TDesignBlazor.Docs.Shared/Pages/Components/MessagePage.razor
  doc/TDesignBlazor.Docs.Shared/Pages/Startup/Index.razor
  readme.md
  src/TDesignBlazor/Components/Messages/IMessageService.cs
  src/TDesignBlazor/Components/Messages/Message.cs
  src/TDesignBlazor/Components/Messages/MessageConfiguration.cs
  src/TDesignBlazor/Components/Messages/MessageContainer.cs
  src/TDesignBlazor/Components/Messages/MessageService.cs
  src/TDesignBlazor/Components/Messages/MessageServiceExtensions.cs
  src/TDesignBlazor/Components/Notification.cs
  src/TDesignBlazor/Components/TDesignContainer.cs
  src/TDesignBlazor/DependencyInjectionExtensions.cs
  src/TDesignBlazor/Enum/Position.cs
  src/TDesignBlazor/TDesignBlazor.csproj
  src/TDesignBlazor/TDesignOptions.cs
  src/TDesignBlazor/wwwroot/tdesign-blazor.css
Labels: 文档, 新功能, 完善

#105 【新增】进度条组件
  .github/workflows/build.yml
  doc/TDesignBlazor.Docs.Shared/Components/Example.razor
  doc/TDesignBlazor.Docs.Shared/Layouts/MainLayout.razor
  doc/TDesignBlazor.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesignBlazor.Docs.Shared/Pages/Components/ProgressPage.razor
  src/TDesignBlazor.Test/Components/ProgressTest.cs
  src/TDesignBlazor/Components/Progress.cs
  src/TDesignBlazor/TDesignBlazor.csproj
  src/TDesignBlazor/TDesignBlazorExtensions.cs
  src/TDesignBlazor/_Imports.cs
  src/TDesignBlazor/wwwroot/images/favicon.ico
  src/TDesignBlazor/wwwroot/images/favicon.png
Labels: 新功能, 评审

#131 【更新】PR 模板的部分内容简化
  .github/PULL_REQUEST_TEMPLATE/Pull_Request_Template.md
  .github/pull_request_template.md
  pull_request_template.md
Labels: 文档

#129 【新增】编译器的代码规范和代码分析脚本
  .editorconfig
  .github/workflows/sonar-code.yml
  TDesignBlazor.sln
  src/TDesignBlazor/TDesignBlazor.csproj
Labels: 完善

#111 【新增】手动添加 master 的 tag 时将自动发布包到 nuget.org
  .github/workflows/auto-release.yml
Labels: DevOps

#133 Button组件的Shape属性新增枚举项 Rectangle 表示长方形按钮
  doc/TDesignBlazor.Docs.Shared/Pages/Components/ButtonPage.razor
  src/TDesignBlazor.Test/Components/ButtonTest.cs
  src/TDesignBlazor/Components/Button.cs
Labels: 完善

#139 【更新】readme 文件以及 workflow 的定义
  .github/workflows/auto-release.yml
  .github/workflows/build.yml
  .github/workflows/pull-request.yml
  readme.md
Labels: DevOps

#148 【更新】pull-request.yml 增加单元测试报告的脚本
  .github/workflows/auto-release.yml
  .github/workflows/git-pages-ci.yml
  .github/workflows/pull-request.yml
Labels: DevOps

#153 【新增】Switch 组件
  doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesign.Docs.Shared/Pages/Components/SwitchPage.razor
  src/TDesign.Test/Components/SwitchTest.cs
  src/TDesign/Components/Forms/TSwitch.cs
Labels: 新功能
