Repository tdesign-blazor/TDesignBlazor, pull requests merged in 2023-06, with the labels that each got.

#288 refactor: 升级 ComponentBuilder 到 4.1
  src/TDesign/Components/Dialog/DialogWrapper.cs
  src/TDesign/Components/Dialog/Templates/ConfirmationDialogTemplate.cs
  src/TDesign/Components/Dialog/Templates/MessageDialogTemplate.cs
  src/TDesign/Components/Forms/TInputTag.cs
  src/TDesign/Components/TPagination.cs
  src/TDesign/Components/TPopConfirm.cs
  src/TDesign/Components/Table/TTable.build.cs
  src/TDesign/Components/Table/TTableCheckboxColumn.cs
  src/TDesign/Components/Timeline/TTimelineItem.cs
  src/TDesign/TDesign.csproj
Labels: enhancement, chore

#289 fix(TPagination): 修复总页数小于2页时的分页条显示错误
  doc/TDesign.Docs.Shared/Pages/TestPage.razor
  src/TDesign/Components/TPagination.cs
Labels: bug

#290 fix(TAlert): 图标无法对齐的问题
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Pages/Components/Notification/AlertPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Notification/NotificationPage.razor
  doc/TDesign.Docs.Shared/Pages/Startup/DesignPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign.Test/Components/Notification/AlertTest.cs
  src/TDesign/Components/Notify/Abstractions/NotifyComponentBase.cs
  src/TDesign/Components/Notify/Messages/TMessage.cs
  src/TDesign/Components/Notify/Notification/TNotification.cs
  src/TDesign/Components/TAlert.cs
  src/TDesign/Interceptors/SpecificationInterceptor.cs
Labels: bug

#291 fix(TMenuItem): 菜单无法根据导航的变化自动高亮
  Contributing.md
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Pages/TestPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  readme.md
  src/TDesign/Components/Menu/TMenuItem.cs
Labels: bug

#293 docs(Contributing):更新了贡献文档
  Contributing.md
Labels: chore

#296 build(tdesign-vue): 更新tdesign-vue版本至1.4.0
  package-lock.json
  package.json
  src/TDesign/wwwroot/tdesign.css
  src/TDesign/wwwroot/tdesign.css.map
  src/TDesign/wwwroot/tdesign.min.css
  src/TDesign/wwwroot/tdesign.min.css.map
  yarn.lock
Labels: feature, upgrade

#301 feat(TButton): 按钮支持图标和文本的效果
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Pages/Components/Basic/ButtonPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign.Test/Components/Basic/ButtonTest.cs
  src/TDesign/Components/TButton.cs
Labels: feature

#302 feat(TButton): 自定义标记渲染的按钮
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Pages/Components/Basic/ButtonPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign.Test/Components/Basic/ButtonTest.cs
  src/TDesign/Components/TButton.cs
Labels: feature, enhancement

#304 feat(TDropdown): 下拉菜单组件
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesign.Docs.Shared/Pages/Components/Navigation/DropdownPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign/Abstractions/FragmentContent.cs
  src/TDesign/Components/Dropdown/DropdownOption.cs
  src/TDesign/Components/Dropdown/TDropdown.cs
  src/TDesign/Components/Popup/TPopup.cs
Labels: feature
