Repository tdesign-blazor/TDesignBlazor, pull requests merged in 2023-01, with the labels that each got.

#218 feat(ci): 新增部署到 Serverless 的脚本
  .github/workflows/deploy-webassembl-artifact.yml
  .github/workflows/git-pages-ci.yml
  .gitignore
Labels: feature, size/M, Small, release/skip, minor, chore

#228 docs: 许可证链接错误，访问404
  readme.md
Labels: bug, document, size/XS, Extra Small

#233 docs: 页脚增加网站域名备案号显示
  doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
Labels: document

#232 docs: 修改了 readme.md 在线演示站点的链接，不再使用github pages
  readme.md
Labels: document, feature, size/XS, Extra Small

#235 chore: 预览站点优化页面样式
  doc/TDesign.Docs.Shared/Layouts/MainLayout.razor
  doc/TDesign.Docs.Shared/wwwroot/app.css
Labels: Extra Small, size/M, chore

#234 refactor: 提供统一的设置js事件的工具方法 tdesign-blazor.js/tdesign.setEvent，并修改了组件…
  src/TDesign/Components/Anchor/TAnchor.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: feature, Extra Small, size/M

#229 feat: 组件table强化，增加（基础的）加载状态
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Pages/Components/TablePage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign/Components/Table/TTable.cs
Labels: feature, enhancement, size/M, Small, minor
