Repository tdesign-blazor/TDesignBlazor, pull requests merged in 2023-03, with the labels that each got.

#246 feat(TTable): 选择行的功能和单选按钮列组件
  doc/TDesign.Docs.ServerSide/Pages/_Layout.cshtml
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Components/HighlightAlert.razor
  doc/TDesign.Docs.Shared/Pages/Components/Data/SkeletonPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor.cs
  doc/TDesign.Docs.Shared/Pages/Components/Input/FormPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputAdornmentPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputCheckboxPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputNumberPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputRadioPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputRangePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputTextAreaPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputTextPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/SelectPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/SwitchPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Navigation/AffixPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Navigation/PaginationPage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Notification/DialogPage.razor
  doc/TDesign.Docs.Shared/Pages/TestPage.razor
  doc/TDesign.Docs.Shared/wwwroot/app.css
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign.Test/Components/Input/InputRadioTest.cs
  src/TDesign/Components/Forms/TInputRadio.cs
  src/TDesign/Components/Forms/TInputRadioContainer.cs
  src/TDesign/Components/Forms/TInputRadioGroup.cs
  src/TDesign/Components/Table/EventArgs/TTableDataRequestEventArgs.cs
  src/TDesign/Components/Table/EventArgs/TTableDataResponseEventArgs.cs
  src/TDesign/Components/Table/EvetArgs/TTableRowItemEventArgs.cs
  src/TDesign/Components/Table/TTable.build.cs
  src/TDesign/Components/Table/TTable.cs
  src/TDesign/Components/Table/TTable.method.cs
  src/TDesign/Components/Table/TTableColumnBase.cs
  src/TDesign/Components/Table/TTableFieldColumn.cs
  src/TDesign/Components/Table/TTableFieldColumnBase.cs
  src/TDesign/Components/Table/TTableRadioColumn.cs
  src/TDesign/TDesignComponentException.cs
Labels: bug, feature, Extra Large, minor, patch, chore, size/XXL

#248 chore: 代码高亮暗色主题
  doc/TDesign.Docs.Shared/wwwroot/app.css
  doc/TDesign.Docs.Shared/wwwroot/styles-github.min.css
Labels: enhancement, size/M, Small, chore

#247 fix: AdditionalStyle 改为 style 使 fixed 样式其生效
  doc/TDesign.Docs.Shared/Layouts/LayoutContent.razor
Labels: bug, size/XS, Extra Small

#251 feat(TTable): 增加 TTableCheckboxColumn 复选框的列
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor
  doc/TDesign.Docs.Shared/Pages/TestPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign/Components/Table/EvetArgs/TTableRowItemEventArgs.cs
  src/TDesign/Components/Table/TTable.cs
  src/TDesign/Components/Table/TTable.method.cs
  src/TDesign/Components/Table/TTableCheckboxColumn.cs
  src/TDesign/Components/Table/TTableColumnBase.cs
  src/TDesign/Components/Table/TTableRadioColumn.cs
Labels: feature, size/L, Large, minor

#252 feat(TTable): 新增展开/收缩的列
  asset/TDesign Pipeline.png
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Components/ComponentAPI.razor
  doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor
  doc/TDesign.Docs.Shared/Pages/TestPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign.Test/Components/Data/TableTest.cs
  src/TDesign/Components/Table/TTable.build.cs
  src/TDesign/Components/Table/TTable.cs
  src/TDesign/Components/Table/TTable.method.cs
  src/TDesign/Components/Table/TTableCell.cs
  src/TDesign/Components/Table/TTableCheckboxColumn.cs
  src/TDesign/Components/Table/TTableColumnBase.cs
  src/TDesign/Components/Table/TTableExpandColumn.cs
  src/TDesign/Components/Table/TTableFieldColumn.cs
  src/TDesign/Components/Table/TTableFieldColumnBase.cs
  src/TDesign/Components/Table/TTableRadioColumn.cs
Labels: feature, Extra Large, size/XL

#254 fix(TPopup): 修复闪动显示的问题
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Pages/TestPage.razor
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign/Components/Popup/Popper.cs
  src/TDesign/Components/Popup/PopperExtensions.cs
  src/TDesign/Components/Popup/PopperOptions.cs
  src/TDesign/Components/Popup/TPopup.cs
  src/TDesign/TDesignExtensions.cs
  src/TDesign/TDesignOptions.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: bug, feature, size/L, Medium, minor

#256 docs: Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/component-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: size/XS, Extra Small, chore

#259 fix:(doc):修改 WebAssembly 的 index.html 的布局
  doc/TDesign.Docs.WebAssembly/wwwroot/app.css
  doc/TDesign.Docs.WebAssembly/wwwroot/index.html
Labels: document, Extra Small, size/S, chore

#258 fix(TPopup): 弹出位置显示不正确
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: bug, Extra Small, size/S, patch

#263 fix: 重构 TTable 的代码实现
  doc/TDesign.Docs.ServerSide/TDesign.xml
  doc/TDesign.Docs.Shared/Components/ComponentAPI.razor
  doc/TDesign.Docs.Shared/Layouts/NavMenu.razor
  doc/TDesign.Docs.Shared/Pages/Components/Data/TablePage.razor
  doc/TDesign.Docs.Shared/Pages/Components/Input/InputTagPage.razor
  doc/TDesign.Docs.Shared/Pages/TestPage.razor
  doc/TDesign.Docs.Shared/wwwroot/app.css
  doc/TDesign.Docs.WebAssembly/wwwroot/TDesign.xml
  src/TDesign.Test/Components/Data/TableTest.cs
  src/TDesign/Components/Forms/TDesignInputComonentBase.cs
  src/TDesign/Components/Forms/TForm.cs
  src/TDesign/Components/Forms/TInputRadio.cs
  src/TDesign/Components/Forms/TInputTag.cs
  src/TDesign/Components/Menu/TMenuItem.cs
  src/TDesign/Components/TTag.cs
  src/TDesign/Components/Table/TTable.build.cs
  src/TDesign/Components/Table/TTable.cs
  src/TDesign/Components/Table/TTable.method.cs
  src/TDesign/Components/Table/TTableCheckboxColumn.cs
  src/TDesign/Components/Table/TTableColumnBase.cs
  src/TDesign/Components/Table/TTableExpandColumn.cs
  src/TDesign/Components/Table/TTableFieldColumn.cs
  src/TDesign/Components/Table/TTableFieldColumnBase.cs
  src/TDesign/Components/Table/TTableRadioColumn.cs
  src/TDesign/Components/Table/TTableRow.cs
  src/TDesign/TDesign.csproj
  src/TDesign/TDesignComponentBase.cs
  src/TDesign/TDesignExtensions.cs
  src/TDesign/Using.cs
  src/TDesign/wwwroot/tdesign-blazor.js
Labels: bug, Extra Large, patch, size/XXL
